package com.blockchain.shipmentstrato.model;

import java.io.Serializable;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;

@DynamoDBTable(tableName = "shipmentstrato")
@EnableAutoConfiguration
public class Shipment implements Serializable {

	private static final long serialVersionUID = 1L;

	private String shipmentId;
	private String shipmentNumber;
	private String shipmentDate;
	private String shipmentTrackingNumber;
	private String dealerId;
	private String dealerOrderId;
	private List<ShipmentItem> shipmentItems;

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	@DynamoDBHashKey(attributeName = "shipmentId")
	@DynamoDBAutoGeneratedKey
	public String getShipmentId() {
		return shipmentId;
	}

	public void setShipmentId(String shipmentId) {
		this.shipmentId = shipmentId;
	}

	@DynamoDBAttribute
	public String getShipmentNumber() {
		return shipmentNumber;
	}

	public void setShipmentNumber(String shipmentNumber) {
		this.shipmentNumber = shipmentNumber;
	}

	@DynamoDBAttribute
	public String getShipmentDate() {
		return shipmentDate;
	}

	public void setShipmentDate(String shipmentDate) {
		this.shipmentDate = shipmentDate;
	}

	@DynamoDBAttribute
	public String getShipmentTrackingNumber() {
		return shipmentTrackingNumber;
	}

	public void setShipmentTrackingNumber(String shipmentTrackingNumber) {
		this.shipmentTrackingNumber = shipmentTrackingNumber;
	}

	@DynamoDBAttribute
	public String getDealerId() {
		return dealerId;
	}

	public void setDealerId(String dealerId) {
		this.dealerId = dealerId;
	}

	@DynamoDBAttribute
	public String getDealerOrderId() {
		return dealerOrderId;
	}

	public void setDealerOrderId(String dealerOrderId) {
		this.dealerOrderId = dealerOrderId;
	}

	@DynamoDBAttribute
	public List<ShipmentItem> getShipmentItems() {
		return shipmentItems;
	}

	public void setShipmentItems(List<ShipmentItem> shipmentItems) {
		this.shipmentItems = shipmentItems;
	}
}
