/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.TransactionResult;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * BatchTransactionResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class BatchTransactionResult {

  @JsonProperty("unBatchTransactionResult")

  private Map<String, List<TransactionResult>> unBatchTransactionResult = new HashMap<>();
  public BatchTransactionResult unBatchTransactionResult(Map<String, List<TransactionResult>> unBatchTransactionResult) {
    this.unBatchTransactionResult = unBatchTransactionResult;
    return this;
  }

  
  public BatchTransactionResult putUnBatchTransactionResultItem(String key, List<TransactionResult> unBatchTransactionResultItem) {
    this.unBatchTransactionResult.put(key, unBatchTransactionResultItem);
    return this;
  }
  /**
  * Get unBatchTransactionResult
  * @return unBatchTransactionResult
  **/
  @Schema(required = true, description = "")
  public Map<String, List<TransactionResult>> getUnBatchTransactionResult() {
    return unBatchTransactionResult;
  }
  public void setUnBatchTransactionResult(Map<String, List<TransactionResult>> unBatchTransactionResult) {
    this.unBatchTransactionResult = unBatchTransactionResult;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchTransactionResult batchTransactionResult = (BatchTransactionResult) o;
    return Objects.equals(this.unBatchTransactionResult, batchTransactionResult.unBatchTransactionResult);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unBatchTransactionResult);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchTransactionResult {\n");
    
    sb.append("    unBatchTransactionResult: ").append(toIndentedString(unBatchTransactionResult)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
