/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.BlockData;
import com.blockchain.shipmentstrato.model.strato.Transaction;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * Block
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class Block {

  @JsonProperty("blockKind")

  private String blockKind = null;

  @JsonProperty("blockBlockUncles")

  private List<BlockData> blockBlockUncles = new ArrayList<>();

  @JsonProperty("blockReceiptTransactions")

  private List<Transaction> blockReceiptTransactions = new ArrayList<>();

  @JsonProperty("blockBlockData")

  private BlockData blockBlockData = null;
  public Block blockKind(String blockKind) {
    this.blockKind = blockKind;
    return this;
  }

  

  /**
  * Get blockKind
  * @return blockKind
  **/
  @Schema(required = true, description = "")
  public String getBlockKind() {
    return blockKind;
  }
  public void setBlockKind(String blockKind) {
    this.blockKind = blockKind;
  }
  public Block blockBlockUncles(List<BlockData> blockBlockUncles) {
    this.blockBlockUncles = blockBlockUncles;
    return this;
  }

  public Block addBlockBlockUnclesItem(BlockData blockBlockUnclesItem) {
    this.blockBlockUncles.add(blockBlockUnclesItem);
    return this;
  }

  /**
  * Get blockBlockUncles
  * @return blockBlockUncles
  **/
  @Schema(required = true, description = "")
  public List<BlockData> getBlockBlockUncles() {
    return blockBlockUncles;
  }
  public void setBlockBlockUncles(List<BlockData> blockBlockUncles) {
    this.blockBlockUncles = blockBlockUncles;
  }
  public Block blockReceiptTransactions(List<Transaction> blockReceiptTransactions) {
    this.blockReceiptTransactions = blockReceiptTransactions;
    return this;
  }

  public Block addBlockReceiptTransactionsItem(Transaction blockReceiptTransactionsItem) {
    this.blockReceiptTransactions.add(blockReceiptTransactionsItem);
    return this;
  }

  /**
  * Get blockReceiptTransactions
  * @return blockReceiptTransactions
  **/
  @Schema(required = true, description = "")
  public List<Transaction> getBlockReceiptTransactions() {
    return blockReceiptTransactions;
  }
  public void setBlockReceiptTransactions(List<Transaction> blockReceiptTransactions) {
    this.blockReceiptTransactions = blockReceiptTransactions;
  }
  public Block blockBlockData(BlockData blockBlockData) {
    this.blockBlockData = blockBlockData;
    return this;
  }

  

  /**
  * Get blockBlockData
  * @return blockBlockData
  **/
  @Schema(required = true, description = "")
  public BlockData getBlockBlockData() {
    return blockBlockData;
  }
  public void setBlockBlockData(BlockData blockBlockData) {
    this.blockBlockData = blockBlockData;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Block block = (Block) o;
    return Objects.equals(this.blockKind, block.blockKind) &&
        Objects.equals(this.blockBlockUncles, block.blockBlockUncles) &&
        Objects.equals(this.blockReceiptTransactions, block.blockReceiptTransactions) &&
        Objects.equals(this.blockBlockData, block.blockBlockData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockKind, blockBlockUncles, blockReceiptTransactions, blockBlockData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Block {\n");
    
    sb.append("    blockKind: ").append(toIndentedString(blockKind)).append("\n");
    sb.append("    blockBlockUncles: ").append(toIndentedString(blockBlockUncles)).append("\n");
    sb.append("    blockReceiptTransactions: ").append(toIndentedString(blockReceiptTransactions)).append("\n");
    sb.append("    blockBlockData: ").append(toIndentedString(blockBlockData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
