/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.ContractDetails;
import com.blockchain.shipmentstrato.model.strato.PostTransaction;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * Bloc Transaction Data
 */
@Schema(description = "Bloc Transaction Data")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class BlocTransactionData {

  @JsonProperty("Send")

  private PostTransaction send = null;

  @JsonProperty("Upload")

  private ContractDetails upload = null;

  @JsonProperty("Call")

  private List<String> call = null;
  public BlocTransactionData send(PostTransaction send) {
    this.send = send;
    return this;
  }

  

  /**
  * Get send
  * @return send
  **/
  @Schema(description = "")
  public PostTransaction getSend() {
    return send;
  }
  public void setSend(PostTransaction send) {
    this.send = send;
  }
  public BlocTransactionData upload(ContractDetails upload) {
    this.upload = upload;
    return this;
  }

  

  /**
  * Get upload
  * @return upload
  **/
  @Schema(description = "")
  public ContractDetails getUpload() {
    return upload;
  }
  public void setUpload(ContractDetails upload) {
    this.upload = upload;
  }
  public BlocTransactionData call(List<String> call) {
    this.call = call;
    return this;
  }

  public BlocTransactionData addCallItem(String callItem) {
    if (this.call == null) {
      this.call = new ArrayList<>();
    }
    this.call.add(callItem);
    return this;
  }

  /**
  * Get call
  * @return call
  **/
  @Schema(description = "")
  public List<String> getCall() {
    return call;
  }
  public void setCall(List<String> call) {
    this.call = call;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlocTransactionData blocTransactionData = (BlocTransactionData) o;
    return Objects.equals(this.send, blocTransactionData.send) &&
        Objects.equals(this.upload, blocTransactionData.upload) &&
        Objects.equals(this.call, blocTransactionData.call);
  }

  @Override
  public int hashCode() {
    return Objects.hash(send, upload, call);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlocTransactionData {\n");
    
    sb.append("    send: ").append(toIndentedString(send)).append("\n");
    sb.append("    upload: ").append(toIndentedString(upload)).append("\n");
    sb.append("    call: ").append(toIndentedString(call)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
