/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.BlocTransactionData;
import com.blockchain.shipmentstrato.model.strato.BlocTransactionStatus;
import com.blockchain.shipmentstrato.model.strato.TransactionResult;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Bloc Transaction Result
 */
@Schema(description = "Bloc Transaction Result")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class BlocTransactionResult {

  @JsonProperty("transactionStatus")

  private BlocTransactionStatus transactionStatus = null;

  @JsonProperty("transactionHash")

  private String transactionHash = null;

  @JsonProperty("transactionTxResult")

  private TransactionResult transactionTxResult = null;

  @JsonProperty("transactionData")

  private BlocTransactionData transactionData = null;
  public BlocTransactionResult transactionStatus(BlocTransactionStatus transactionStatus) {
    this.transactionStatus = transactionStatus;
    return this;
  }

  

  /**
  * Get transactionStatus
  * @return transactionStatus
  **/
  @Schema(required = true, description = "")
  public BlocTransactionStatus getTransactionStatus() {
    return transactionStatus;
  }
  public void setTransactionStatus(BlocTransactionStatus transactionStatus) {
    this.transactionStatus = transactionStatus;
  }
  public BlocTransactionResult transactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
    return this;
  }

  

  /**
  * Get transactionHash
  * @return transactionHash
  **/
  @Schema(required = true, description = "")
  public String getTransactionHash() {
    return transactionHash;
  }
  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }
  public BlocTransactionResult transactionTxResult(TransactionResult transactionTxResult) {
    this.transactionTxResult = transactionTxResult;
    return this;
  }

  

  /**
  * Get transactionTxResult
  * @return transactionTxResult
  **/
  @Schema(description = "")
  public TransactionResult getTransactionTxResult() {
    return transactionTxResult;
  }
  public void setTransactionTxResult(TransactionResult transactionTxResult) {
    this.transactionTxResult = transactionTxResult;
  }
  public BlocTransactionResult transactionData(BlocTransactionData transactionData) {
    this.transactionData = transactionData;
    return this;
  }

  

  /**
  * Get transactionData
  * @return transactionData
  **/
  @Schema(description = "")
  public BlocTransactionData getTransactionData() {
    return transactionData;
  }
  public void setTransactionData(BlocTransactionData transactionData) {
    this.transactionData = transactionData;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlocTransactionResult blocTransactionResult = (BlocTransactionResult) o;
    return Objects.equals(this.transactionStatus, blocTransactionResult.transactionStatus) &&
        Objects.equals(this.transactionHash, blocTransactionResult.transactionHash) &&
        Objects.equals(this.transactionTxResult, blocTransactionResult.transactionTxResult) &&
        Objects.equals(this.transactionData, blocTransactionResult.transactionData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionStatus, transactionHash, transactionTxResult, transactionData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlocTransactionResult {\n");
    
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    transactionTxResult: ").append(toIndentedString(transactionTxResult)).append("\n");
    sb.append("    transactionData: ").append(toIndentedString(transactionData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
