/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.ContractPayload;
import com.blockchain.shipmentstrato.model.strato.FunctionPayload;
import com.blockchain.shipmentstrato.model.strato.TransferPayload;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Bloc Transaction Payload
 */
@Schema(description = "Bloc Transaction Payload")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class BlocTransactionPayload {

  @JsonProperty("BlocTransfer")

  private TransferPayload blocTransfer = null;

  @JsonProperty("BlocContract")

  private ContractPayload blocContract = null;

  @JsonProperty("BlocFunction")

  private FunctionPayload blocFunction = null;
  public BlocTransactionPayload blocTransfer(TransferPayload blocTransfer) {
    this.blocTransfer = blocTransfer;
    return this;
  }

  

  /**
  * Get blocTransfer
  * @return blocTransfer
  **/
  @Schema(description = "")
  public TransferPayload getBlocTransfer() {
    return blocTransfer;
  }
  public void setBlocTransfer(TransferPayload blocTransfer) {
    this.blocTransfer = blocTransfer;
  }
  public BlocTransactionPayload blocContract(ContractPayload blocContract) {
    this.blocContract = blocContract;
    return this;
  }

  

  /**
  * Get blocContract
  * @return blocContract
  **/
  @Schema(description = "")
  public ContractPayload getBlocContract() {
    return blocContract;
  }
  public void setBlocContract(ContractPayload blocContract) {
    this.blocContract = blocContract;
  }
  public BlocTransactionPayload blocFunction(FunctionPayload blocFunction) {
    this.blocFunction = blocFunction;
    return this;
  }

  

  /**
  * Get blocFunction
  * @return blocFunction
  **/
  @Schema(description = "")
  public FunctionPayload getBlocFunction() {
    return blocFunction;
  }
  public void setBlocFunction(FunctionPayload blocFunction) {
    this.blocFunction = blocFunction;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlocTransactionPayload blocTransactionPayload = (BlocTransactionPayload) o;
    return Objects.equals(this.blocTransfer, blocTransactionPayload.blocTransfer) &&
        Objects.equals(this.blocContract, blocTransactionPayload.blocContract) &&
        Objects.equals(this.blocFunction, blocTransactionPayload.blocFunction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blocTransfer, blocContract, blocFunction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlocTransactionPayload {\n");
    
    sb.append("    blocTransfer: ").append(toIndentedString(blocTransfer)).append("\n");
    sb.append("    blocContract: ").append(toIndentedString(blocContract)).append("\n");
    sb.append("    blocFunction: ").append(toIndentedString(blocFunction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
