/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;

/**
 * ChainSignature
 */
@Schema(description = "ChainSignature")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class ChainSignature {

  @JsonProperty("r")

  private String r = null;

  @JsonProperty("s")

  private String s = null;

  @JsonProperty("v")

  private File v = null;
  public ChainSignature r(String r) {
    this.r = r;
    return this;
  }

  

  /**
  * Get r
  * @return r
  **/
  @Schema(required = true, description = "")
  public String getR() {
    return r;
  }
  public void setR(String r) {
    this.r = r;
  }
  public ChainSignature s(String s) {
    this.s = s;
    return this;
  }

  

  /**
  * Get s
  * @return s
  **/
  @Schema(required = true, description = "")
  public String getS() {
    return s;
  }
  public void setS(String s) {
    this.s = s;
  }
  public ChainSignature v(File v) {
    this.v = v;
    return this;
  }

  

  /**
  * Get v
  * @return v
  **/
  @Schema(required = true, description = "")
  public File getV() {
    return v;
  }
  public void setV(File v) {
    this.v = v;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChainSignature chainSignature = (ChainSignature) o;
    return Objects.equals(this.r, chainSignature.r) &&
        Objects.equals(this.s, chainSignature.s) &&
        Objects.equals(this.v, chainSignature.v);
  }

  @Override
  public int hashCode() {
    return Objects.hash(r, s, v);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChainSignature {\n");
    
    sb.append("    r: ").append(toIndentedString(r)).append("\n");
    sb.append("    s: ").append(toIndentedString(s)).append("\n");
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
