/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.NamedTuple;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * Chain Output Info
 */
@Schema(description = "Chain Output Info")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class ChainOutput {

  @JsonProperty("label")

  private String label = null;

  @JsonProperty("balances")

  private List<NamedTuple> balances = new ArrayList<>();

  @JsonProperty("members")

  private List<NamedTuple> members = new ArrayList<>();
  public ChainOutput label(String label) {
    this.label = label;
    return this;
  }

  

  /**
  * Get label
  * @return label
  **/
  @Schema(required = true, description = "")
  public String getLabel() {
    return label;
  }
  public void setLabel(String label) {
    this.label = label;
  }
  public ChainOutput balances(List<NamedTuple> balances) {
    this.balances = balances;
    return this;
  }

  public ChainOutput addBalancesItem(NamedTuple balancesItem) {
    this.balances.add(balancesItem);
    return this;
  }

  /**
  * Get balances
  * @return balances
  **/
  @Schema(required = true, description = "")
  public List<NamedTuple> getBalances() {
    return balances;
  }
  public void setBalances(List<NamedTuple> balances) {
    this.balances = balances;
  }
  public ChainOutput members(List<NamedTuple> members) {
    this.members = members;
    return this;
  }

  public ChainOutput addMembersItem(NamedTuple membersItem) {
    this.members.add(membersItem);
    return this;
  }

  /**
  * Get members
  * @return members
  **/
  @Schema(required = true, description = "")
  public List<NamedTuple> getMembers() {
    return members;
  }
  public void setMembers(List<NamedTuple> members) {
    this.members = members;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChainOutput chainOutput = (ChainOutput) o;
    return Objects.equals(this.label, chainOutput.label) &&
        Objects.equals(this.balances, chainOutput.balances) &&
        Objects.equals(this.members, chainOutput.members);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, balances, members);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChainOutput {\n");
    
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    balances: ").append(toIndentedString(balances)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
