/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Contract Payload
 */
@Schema(description = "Contract Payload")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class ContractPayload {

  @JsonProperty("src")

  private String src = null;

  @JsonProperty("contract")

  private String contract = null;

  @JsonProperty("args")

  private Map<String, String> args = null;

  @JsonProperty("value")

  private Integer value = null;

  @JsonProperty("metadata")

  private Map<String, String> metadata = null;
  public ContractPayload src(String src) {
    this.src = src;
    return this;
  }

  

  /**
  * Get src
  * @return src
  **/
  @Schema(required = true, description = "")
  public String getSrc() {
    return src;
  }
  public void setSrc(String src) {
    this.src = src;
  }
  public ContractPayload contract(String contract) {
    this.contract = contract;
    return this;
  }

  

  /**
  * Get contract
  * @return contract
  **/
  @Schema(description = "")
  public String getContract() {
    return contract;
  }
  public void setContract(String contract) {
    this.contract = contract;
  }
  public ContractPayload args(Map<String, String> args) {
    this.args = args;
    return this;
  }

  
  public ContractPayload putArgsItem(String key, String argsItem) {
    if (this.args == null) {
      this.args = new HashMap<>();
    }
    this.args.put(key, argsItem);
    return this;
  }
  /**
  * Get args
  * @return args
  **/
  @Schema(description = "")
  public Map<String, String> getArgs() {
    return args;
  }
  public void setArgs(Map<String, String> args) {
    this.args = args;
  }
  public ContractPayload value(Integer value) {
    this.value = value;
    return this;
  }

  

  /**
  * Get value
  * minimum: 0
  * @return value
  **/
  @Schema(description = "")
  public Integer getValue() {
    return value;
  }
  public void setValue(Integer value) {
    this.value = value;
  }
  public ContractPayload metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  
  public ContractPayload putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }
  /**
  * Get metadata
  * @return metadata
  **/
  @Schema(description = "")
  public Map<String, String> getMetadata() {
    return metadata;
  }
  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractPayload contractPayload = (ContractPayload) o;
    return Objects.equals(this.src, contractPayload.src) &&
        Objects.equals(this.contract, contractPayload.contract) &&
        Objects.equals(this.args, contractPayload.args) &&
        Objects.equals(this.value, contractPayload.value) &&
        Objects.equals(this.metadata, contractPayload.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(src, contract, args, value, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractPayload {\n");
    
    sb.append("    src: ").append(toIndentedString(src)).append("\n");
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
