/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Contract
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class Contract {

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("codeHash")

  private String codeHash = null;

  @JsonProperty("contract")

  private String contract = null;

  @JsonProperty("abi")

  private String abi = null;

  @JsonProperty("chainId")

  private String chainId = null;
  public Contract id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * Note: This is a Primary Key.
  * @return id
  **/
  @Schema(description = "Note: This is a Primary Key.")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public Contract codeHash(String codeHash) {
    this.codeHash = codeHash;
    return this;
  }

  

  /**
  * Get codeHash
  * @return codeHash
  **/
  @Schema(description = "")
  public String getCodeHash() {
    return codeHash;
  }
  public void setCodeHash(String codeHash) {
    this.codeHash = codeHash;
  }
  public Contract contract(String contract) {
    this.contract = contract;
    return this;
  }

  

  /**
  * Get contract
  * @return contract
  **/
  @Schema(description = "")
  public String getContract() {
    return contract;
  }
  public void setContract(String contract) {
    this.contract = contract;
  }
  public Contract abi(String abi) {
    this.abi = abi;
    return this;
  }

  

  /**
  * Get abi
  * @return abi
  **/
  @Schema(description = "")
  public String getAbi() {
    return abi;
  }
  public void setAbi(String abi) {
    this.abi = abi;
  }
  public Contract chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

  

  /**
  * Get chainId
  * @return chainId
  **/
  @Schema(description = "")
  public String getChainId() {
    return chainId;
  }
  public void setChainId(String chainId) {
    this.chainId = chainId;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Contract contract = (Contract) o;
    return Objects.equals(this.id, contract.id) &&
        Objects.equals(this.codeHash, contract.codeHash) &&
        Objects.equals(this.contract, contract.contract) &&
        Objects.equals(this.abi, contract.abi) &&
        Objects.equals(this.chainId, contract.chainId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, codeHash, contract, abi, chainId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Contract {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    codeHash: ").append(toIndentedString(codeHash)).append("\n");
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("    abi: ").append(toIndentedString(abi)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
