/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.XabiSchema;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Returned data from contract creation.
 */
@Schema(description = "Returned data from contract creation.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class ContractDetails {

  @JsonProperty("bin")

  private String bin = null;

  @JsonProperty("address")

  private String address = null;

  @JsonProperty("binRuntime")

  private String binRuntime = null;

  @JsonProperty("codeHash")

  private String codeHash = null;

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("src")

  private String src = null;

  @JsonProperty("xabi")

  private XabiSchema xabi = null;

  @JsonProperty("chainId")

  private String chainId = null;
  public ContractDetails bin(String bin) {
    this.bin = bin;
    return this;
  }

  

  /**
  * Get bin
  * @return bin
  **/
  @Schema(required = true, description = "")
  public String getBin() {
    return bin;
  }
  public void setBin(String bin) {
    this.bin = bin;
  }
  public ContractDetails address(String address) {
    this.address = address;
    return this;
  }

  

  /**
  * Get address
  * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }
  public ContractDetails binRuntime(String binRuntime) {
    this.binRuntime = binRuntime;
    return this;
  }

  

  /**
  * Get binRuntime
  * @return binRuntime
  **/
  @Schema(required = true, description = "")
  public String getBinRuntime() {
    return binRuntime;
  }
  public void setBinRuntime(String binRuntime) {
    this.binRuntime = binRuntime;
  }
  public ContractDetails codeHash(String codeHash) {
    this.codeHash = codeHash;
    return this;
  }

  

  /**
  * Get codeHash
  * @return codeHash
  **/
  @Schema(required = true, description = "")
  public String getCodeHash() {
    return codeHash;
  }
  public void setCodeHash(String codeHash) {
    this.codeHash = codeHash;
  }
  public ContractDetails name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public ContractDetails src(String src) {
    this.src = src;
    return this;
  }

  

  /**
  * Get src
  * @return src
  **/
  @Schema(required = true, description = "")
  public String getSrc() {
    return src;
  }
  public void setSrc(String src) {
    this.src = src;
  }
  public ContractDetails xabi(XabiSchema xabi) {
    this.xabi = xabi;
    return this;
  }

  

  /**
  * Get xabi
  * @return xabi
  **/
  @Schema(required = true, description = "")
  public XabiSchema getXabi() {
    return xabi;
  }
  public void setXabi(XabiSchema xabi) {
    this.xabi = xabi;
  }
  public ContractDetails chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

  

  /**
  * Get chainId
  * @return chainId
  **/
  @Schema(description = "")
  public String getChainId() {
    return chainId;
  }
  public void setChainId(String chainId) {
    this.chainId = chainId;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractDetails contractDetails = (ContractDetails) o;
    return Objects.equals(this.bin, contractDetails.bin) &&
        Objects.equals(this.address, contractDetails.address) &&
        Objects.equals(this.binRuntime, contractDetails.binRuntime) &&
        Objects.equals(this.codeHash, contractDetails.codeHash) &&
        Objects.equals(this.name, contractDetails.name) &&
        Objects.equals(this.src, contractDetails.src) &&
        Objects.equals(this.xabi, contractDetails.xabi) &&
        Objects.equals(this.chainId, contractDetails.chainId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bin, address, binRuntime, codeHash, name, src, xabi, chainId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractDetails {\n");
    
    sb.append("    bin: ").append(toIndentedString(bin)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    binRuntime: ").append(toIndentedString(binRuntime)).append("\n");
    sb.append("    codeHash: ").append(toIndentedString(codeHash)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    src: ").append(toIndentedString(src)).append("\n");
    sb.append("    xabi: ").append(toIndentedString(xabi)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
