/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.SolidityType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * Xabi Event
 */
@Schema(description = "Xabi Event")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class EventSchema {

  @JsonProperty("anonymous")

  private Boolean anonymous = null;

  @JsonProperty("logs")

  private List<List<SolidityType>> logs = new ArrayList<>();
  public EventSchema anonymous(Boolean anonymous) {
    this.anonymous = anonymous;
    return this;
  }

  

  /**
  * Get anonymous
  * @return anonymous
  **/
  @Schema(required = true, description = "")
  public Boolean isAnonymous() {
    return anonymous;
  }
  public void setAnonymous(Boolean anonymous) {
    this.anonymous = anonymous;
  }
  public EventSchema logs(List<List<SolidityType>> logs) {
    this.logs = logs;
    return this;
  }

  public EventSchema addLogsItem(List<SolidityType> logsItem) {
    this.logs.add(logsItem);
    return this;
  }

  /**
  * Get logs
  * @return logs
  **/
  @Schema(required = true, description = "")
  public List<List<SolidityType>> getLogs() {
    return logs;
  }
  public void setLogs(List<List<SolidityType>> logs) {
    this.logs = logs;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventSchema eventSchema = (EventSchema) o;
    return Objects.equals(this.anonymous, eventSchema.anonymous) &&
        Objects.equals(this.logs, eventSchema.logs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anonymous, logs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventSchema {\n");
    
    sb.append("    anonymous: ").append(toIndentedString(anonymous)).append("\n");
    sb.append("    logs: ").append(toIndentedString(logs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
