/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * FileList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class FileList {

  @JsonProperty("contractAddress")

  private String contractAddress = null;

  @JsonProperty("uri")

  private String uri = null;

  @JsonProperty("hash")

  private String hash = null;

  @JsonProperty("createdAt")

  private Double createdAt = null;
  public FileList contractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
    return this;
  }

  

  /**
  * Get contractAddress
  * @return contractAddress
  **/
  @Schema(description = "")
  public String getContractAddress() {
    return contractAddress;
  }
  public void setContractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
  }
  public FileList uri(String uri) {
    this.uri = uri;
    return this;
  }

  

  /**
  * Get uri
  * @return uri
  **/
  @Schema(description = "")
  public String getUri() {
    return uri;
  }
  public void setUri(String uri) {
    this.uri = uri;
  }
  public FileList hash(String hash) {
    this.hash = hash;
    return this;
  }

  

  /**
  * Get hash
  * @return hash
  **/
  @Schema(description = "")
  public String getHash() {
    return hash;
  }
  public void setHash(String hash) {
    this.hash = hash;
  }
  public FileList createdAt(Double createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  

  /**
  * Get createdAt
  * @return createdAt
  **/
  @Schema(description = "")
  public Double getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(Double createdAt) {
    this.createdAt = createdAt;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileList fileList = (FileList) o;
    return Objects.equals(this.contractAddress, fileList.contractAddress) &&
        Objects.equals(this.uri, fileList.uri) &&
        Objects.equals(this.hash, fileList.hash) &&
        Objects.equals(this.createdAt, fileList.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractAddress, uri, hash, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileList {\n");
    
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
