/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.SolidityType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Xabi Function Modifier
 */
@Schema(description = "Xabi Function Modifier")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class FunctionModifier {

  @JsonProperty("args")

  private Map<String, SolidityType> args = new HashMap<>();

  @JsonProperty("selector")

  private String selector = null;

  @JsonProperty("vals")

  private Map<String, SolidityType> vals = new HashMap<>();

  @JsonProperty("contents")

  private String contents = null;
  public FunctionModifier args(Map<String, SolidityType> args) {
    this.args = args;
    return this;
  }

  
  public FunctionModifier putArgsItem(String key, SolidityType argsItem) {
    this.args.put(key, argsItem);
    return this;
  }
  /**
  * Get args
  * @return args
  **/
  @Schema(required = true, description = "")
  public Map<String, SolidityType> getArgs() {
    return args;
  }
  public void setArgs(Map<String, SolidityType> args) {
    this.args = args;
  }
  public FunctionModifier selector(String selector) {
    this.selector = selector;
    return this;
  }

  

  /**
  * Get selector
  * @return selector
  **/
  @Schema(required = true, description = "")
  public String getSelector() {
    return selector;
  }
  public void setSelector(String selector) {
    this.selector = selector;
  }
  public FunctionModifier vals(Map<String, SolidityType> vals) {
    this.vals = vals;
    return this;
  }

  
  public FunctionModifier putValsItem(String key, SolidityType valsItem) {
    this.vals.put(key, valsItem);
    return this;
  }
  /**
  * Get vals
  * @return vals
  **/
  @Schema(required = true, description = "")
  public Map<String, SolidityType> getVals() {
    return vals;
  }
  public void setVals(Map<String, SolidityType> vals) {
    this.vals = vals;
  }
  public FunctionModifier contents(String contents) {
    this.contents = contents;
    return this;
  }

  

  /**
  * Get contents
  * @return contents
  **/
  @Schema(description = "")
  public String getContents() {
    return contents;
  }
  public void setContents(String contents) {
    this.contents = contents;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionModifier functionModifier = (FunctionModifier) o;
    return Objects.equals(this.args, functionModifier.args) &&
        Objects.equals(this.selector, functionModifier.selector) &&
        Objects.equals(this.vals, functionModifier.vals) &&
        Objects.equals(this.contents, functionModifier.contents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(args, selector, vals, contents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionModifier {\n");
    
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("    vals: ").append(toIndentedString(vals)).append("\n");
    sb.append("    contents: ").append(toIndentedString(contents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
