/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Function Payload
 */
@Schema(description = "Function Payload")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class FunctionPayload {

  @JsonProperty("contractName")

  private String contractName = null;

  @JsonProperty("contractAddress")

  private String contractAddress = null;

  @JsonProperty("method")

  private String method = null;

  @JsonProperty("args")

  private Map<String, String> args = new HashMap<>();

  @JsonProperty("value")

  private Integer value = null;

  @JsonProperty("metadata")

  private Map<String, String> metadata = null;
  public FunctionPayload contractName(String contractName) {
    this.contractName = contractName;
    return this;
  }

  

  /**
  * Get contractName
  * @return contractName
  **/
  @Schema(required = true, description = "")
  public String getContractName() {
    return contractName;
  }
  public void setContractName(String contractName) {
    this.contractName = contractName;
  }
  public FunctionPayload contractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
    return this;
  }

  

  /**
  * Get contractAddress
  * @return contractAddress
  **/
  @Schema(required = true, description = "")
  public String getContractAddress() {
    return contractAddress;
  }
  public void setContractAddress(String contractAddress) {
    this.contractAddress = contractAddress;
  }
  public FunctionPayload method(String method) {
    this.method = method;
    return this;
  }

  

  /**
  * Get method
  * @return method
  **/
  @Schema(required = true, description = "")
  public String getMethod() {
    return method;
  }
  public void setMethod(String method) {
    this.method = method;
  }
  public FunctionPayload args(Map<String, String> args) {
    this.args = args;
    return this;
  }

  
  public FunctionPayload putArgsItem(String key, String argsItem) {
    this.args.put(key, argsItem);
    return this;
  }
  /**
  * Get args
  * @return args
  **/
  @Schema(required = true, description = "")
  public Map<String, String> getArgs() {
    return args;
  }
  public void setArgs(Map<String, String> args) {
    this.args = args;
  }
  public FunctionPayload value(Integer value) {
    this.value = value;
    return this;
  }

  

  /**
  * Get value
  * minimum: 0
  * @return value
  **/
  @Schema(description = "")
  public Integer getValue() {
    return value;
  }
  public void setValue(Integer value) {
    this.value = value;
  }
  public FunctionPayload metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  
  public FunctionPayload putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }
  /**
  * Get metadata
  * @return metadata
  **/
  @Schema(description = "")
  public Map<String, String> getMetadata() {
    return metadata;
  }
  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionPayload functionPayload = (FunctionPayload) o;
    return Objects.equals(this.contractName, functionPayload.contractName) &&
        Objects.equals(this.contractAddress, functionPayload.contractAddress) &&
        Objects.equals(this.method, functionPayload.method) &&
        Objects.equals(this.args, functionPayload.args) &&
        Objects.equals(this.value, functionPayload.value) &&
        Objects.equals(this.metadata, functionPayload.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractName, contractAddress, method, args, value, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionPayload {\n");
    
    sb.append("    contractName: ").append(toIndentedString(contractName)).append("\n");
    sb.append("    contractAddress: ").append(toIndentedString(contractAddress)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
