/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.KeyStoreEntry;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * KeyStoreEntry
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class KeyStoreEntry {

  @JsonProperty("password")

  private String password = null;

  @JsonProperty("keyStore")

  private KeyStoreEntry keyStore = null;
  public KeyStoreEntry password(String password) {
    this.password = password;
    return this;
  }

  

  /**
  * Get password
  * @return password
  **/
  @Schema(required = true, description = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }
  public KeyStoreEntry keyStore(KeyStoreEntry keyStore) {
    this.keyStore = keyStore;
    return this;
  }

  

  /**
  * Get keyStore
  * @return keyStore
  **/
  @Schema(required = true, description = "")
  public KeyStoreEntry getKeyStore() {
    return keyStore;
  }
  public void setKeyStore(KeyStoreEntry keyStore) {
    this.keyStore = keyStore;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyStoreEntry keyStoreEntry = (KeyStoreEntry) o;
    return Objects.equals(this.password, keyStoreEntry.password) &&
        Objects.equals(this.keyStore, keyStoreEntry.keyStore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, keyStore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyStoreEntry {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    keyStore: ").append(toIndentedString(keyStore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
