/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.BlocTransactionPayload;
import com.blockchain.shipmentstrato.model.strato.TransactionParameters;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * Post Bloc Transaction Request
 */
@Schema(description = "Post Bloc Transaction Request")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class PostBlocTransactionRequest {

  @JsonProperty("address")

  private String address = null;

  @JsonProperty("txs")

  private List<BlocTransactionPayload> txs = new ArrayList<>();

  @JsonProperty("txParams")

  private TransactionParameters txParams = null;
  public PostBlocTransactionRequest address(String address) {
    this.address = address;
    return this;
  }

  

  /**
  * Get address
  * @return address
  **/
  @Schema(description = "")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }
  public PostBlocTransactionRequest txs(List<BlocTransactionPayload> txs) {
    this.txs = txs;
    return this;
  }

  public PostBlocTransactionRequest addTxsItem(BlocTransactionPayload txsItem) {
    this.txs.add(txsItem);
    return this;
  }

  /**
  * Get txs
  * @return txs
  **/
  @Schema(required = true, description = "")
  public List<BlocTransactionPayload> getTxs() {
    return txs;
  }
  public void setTxs(List<BlocTransactionPayload> txs) {
    this.txs = txs;
  }
  public PostBlocTransactionRequest txParams(TransactionParameters txParams) {
    this.txParams = txParams;
    return this;
  }

  

  /**
  * Get txParams
  * @return txParams
  **/
  @Schema(description = "")
  public TransactionParameters getTxParams() {
    return txParams;
  }
  public void setTxParams(TransactionParameters txParams) {
    this.txParams = txParams;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostBlocTransactionRequest postBlocTransactionRequest = (PostBlocTransactionRequest) o;
    return Objects.equals(this.address, postBlocTransactionRequest.address) &&
        Objects.equals(this.txs, postBlocTransactionRequest.txs) &&
        Objects.equals(this.txParams, postBlocTransactionRequest.txParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, txs, txParams);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostBlocTransactionRequest {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    txs: ").append(toIndentedString(txs)).append("\n");
    sb.append("    txParams: ").append(toIndentedString(txParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
