/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.TransactionParameters;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Post Users Contract Method Request
 */
@Schema(description = "Post Users Contract Method Request")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class PostUsersContractMethodRequest {

  @JsonProperty("password")

  private String password = null;

  @JsonProperty("method")

  private String method = null;

  @JsonProperty("args")

  private Map<String, String> args = new HashMap<>();

  @JsonProperty("value")

  private String value = null;

  @JsonProperty("txParams")

  private TransactionParameters txParams = null;

  @JsonProperty("metadata")

  private Map<String, String> metadata = null;
  public PostUsersContractMethodRequest password(String password) {
    this.password = password;
    return this;
  }

  

  /**
  * Get password
  * @return password
  **/
  @Schema(required = true, description = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }
  public PostUsersContractMethodRequest method(String method) {
    this.method = method;
    return this;
  }

  

  /**
  * Method name
  * @return method
  **/
  @Schema(required = true, description = "Method name")
  public String getMethod() {
    return method;
  }
  public void setMethod(String method) {
    this.method = method;
  }
  public PostUsersContractMethodRequest args(Map<String, String> args) {
    this.args = args;
    return this;
  }

  
  public PostUsersContractMethodRequest putArgsItem(String key, String argsItem) {
    this.args.put(key, argsItem);
    return this;
  }
  /**
  * Get args
  * @return args
  **/
  @Schema(required = true, description = "")
  public Map<String, String> getArgs() {
    return args;
  }
  public void setArgs(Map<String, String> args) {
    this.args = args;
  }
  public PostUsersContractMethodRequest value(String value) {
    this.value = value;
    return this;
  }

  

  /**
  * Method value in Eth
  * @return value
  **/
  @Schema(description = "Method value in Eth")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }
  public PostUsersContractMethodRequest txParams(TransactionParameters txParams) {
    this.txParams = txParams;
    return this;
  }

  

  /**
  * Get txParams
  * @return txParams
  **/
  @Schema(description = "")
  public TransactionParameters getTxParams() {
    return txParams;
  }
  public void setTxParams(TransactionParameters txParams) {
    this.txParams = txParams;
  }
  public PostUsersContractMethodRequest metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  
  public PostUsersContractMethodRequest putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }
  /**
  * Get metadata
  * @return metadata
  **/
  @Schema(description = "")
  public Map<String, String> getMetadata() {
    return metadata;
  }
  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostUsersContractMethodRequest postUsersContractMethodRequest = (PostUsersContractMethodRequest) o;
    return Objects.equals(this.password, postUsersContractMethodRequest.password) &&
        Objects.equals(this.method, postUsersContractMethodRequest.method) &&
        Objects.equals(this.args, postUsersContractMethodRequest.args) &&
        Objects.equals(this.value, postUsersContractMethodRequest.value) &&
        Objects.equals(this.txParams, postUsersContractMethodRequest.txParams) &&
        Objects.equals(this.metadata, postUsersContractMethodRequest.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, method, args, value, txParams, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostUsersContractMethodRequest {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    args: ").append(toIndentedString(args)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    txParams: ").append(toIndentedString(txParams)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
