/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Post Transaction
 */
@Schema(description = "Post Transaction")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class PostTransaction {

  @JsonProperty("hash")

  private String hash = null;

  @JsonProperty("gasLimit")

  private Integer gasLimit = null;

  @JsonProperty("codeOrData")

  private String codeOrData = null;

  @JsonProperty("gasPrice")

  private Integer gasPrice = null;

  @JsonProperty("to")

  private String to = null;

  @JsonProperty("from")

  private String from = null;

  @JsonProperty("value")

  private Integer value = null;

  @JsonProperty("r")

  private String r = null;

  @JsonProperty("s")

  private String s = null;

  @JsonProperty("v")

  private File v = null;

  @JsonProperty("nonce")

  private Integer nonce = null;

  @JsonProperty("chainId")

  private String chainId = null;

  @JsonProperty("metadata")

  private Map<String, String> metadata = null;
  public PostTransaction hash(String hash) {
    this.hash = hash;
    return this;
  }

  

  /**
  * Get hash
  * @return hash
  **/
  @Schema(required = true, description = "")
  public String getHash() {
    return hash;
  }
  public void setHash(String hash) {
    this.hash = hash;
  }
  public PostTransaction gasLimit(Integer gasLimit) {
    this.gasLimit = gasLimit;
    return this;
  }

  

  /**
  * Get gasLimit
  * minimum: 0
  * @return gasLimit
  **/
  @Schema(required = true, description = "")
  public Integer getGasLimit() {
    return gasLimit;
  }
  public void setGasLimit(Integer gasLimit) {
    this.gasLimit = gasLimit;
  }
  public PostTransaction codeOrData(String codeOrData) {
    this.codeOrData = codeOrData;
    return this;
  }

  

  /**
  * Get codeOrData
  * @return codeOrData
  **/
  @Schema(required = true, description = "")
  public String getCodeOrData() {
    return codeOrData;
  }
  public void setCodeOrData(String codeOrData) {
    this.codeOrData = codeOrData;
  }
  public PostTransaction gasPrice(Integer gasPrice) {
    this.gasPrice = gasPrice;
    return this;
  }

  

  /**
  * Get gasPrice
  * minimum: 0
  * @return gasPrice
  **/
  @Schema(required = true, description = "")
  public Integer getGasPrice() {
    return gasPrice;
  }
  public void setGasPrice(Integer gasPrice) {
    this.gasPrice = gasPrice;
  }
  public PostTransaction to(String to) {
    this.to = to;
    return this;
  }

  

  /**
  * Get to
  * @return to
  **/
  @Schema(description = "")
  public String getTo() {
    return to;
  }
  public void setTo(String to) {
    this.to = to;
  }
  public PostTransaction from(String from) {
    this.from = from;
    return this;
  }

  

  /**
  * Get from
  * @return from
  **/
  @Schema(required = true, description = "")
  public String getFrom() {
    return from;
  }
  public void setFrom(String from) {
    this.from = from;
  }
  public PostTransaction value(Integer value) {
    this.value = value;
    return this;
  }

  

  /**
  * Get value
  * minimum: 0
  * @return value
  **/
  @Schema(required = true, description = "")
  public Integer getValue() {
    return value;
  }
  public void setValue(Integer value) {
    this.value = value;
  }
  public PostTransaction r(String r) {
    this.r = r;
    return this;
  }

  

  /**
  * Get r
  * @return r
  **/
  @Schema(required = true, description = "")
  public String getR() {
    return r;
  }
  public void setR(String r) {
    this.r = r;
  }
  public PostTransaction s(String s) {
    this.s = s;
    return this;
  }

  

  /**
  * Get s
  * @return s
  **/
  @Schema(required = true, description = "")
  public String getS() {
    return s;
  }
  public void setS(String s) {
    this.s = s;
  }
  public PostTransaction v(File v) {
    this.v = v;
    return this;
  }

  

  /**
  * Get v
  * @return v
  **/
  @Schema(required = true, description = "")
  public File getV() {
    return v;
  }
  public void setV(File v) {
    this.v = v;
  }
  public PostTransaction nonce(Integer nonce) {
    this.nonce = nonce;
    return this;
  }

  

  /**
  * Get nonce
  * minimum: 0
  * @return nonce
  **/
  @Schema(required = true, description = "")
  public Integer getNonce() {
    return nonce;
  }
  public void setNonce(Integer nonce) {
    this.nonce = nonce;
  }
  public PostTransaction chainId(String chainId) {
    this.chainId = chainId;
    return this;
  }

  

  /**
  * Get chainId
  * @return chainId
  **/
  @Schema(description = "")
  public String getChainId() {
    return chainId;
  }
  public void setChainId(String chainId) {
    this.chainId = chainId;
  }
  public PostTransaction metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  
  public PostTransaction putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }
  /**
  * Get metadata
  * @return metadata
  **/
  @Schema(description = "")
  public Map<String, String> getMetadata() {
    return metadata;
  }
  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostTransaction postTransaction = (PostTransaction) o;
    return Objects.equals(this.hash, postTransaction.hash) &&
        Objects.equals(this.gasLimit, postTransaction.gasLimit) &&
        Objects.equals(this.codeOrData, postTransaction.codeOrData) &&
        Objects.equals(this.gasPrice, postTransaction.gasPrice) &&
        Objects.equals(this.to, postTransaction.to) &&
        Objects.equals(this.from, postTransaction.from) &&
        Objects.equals(this.value, postTransaction.value) &&
        Objects.equals(this.r, postTransaction.r) &&
        Objects.equals(this.s, postTransaction.s) &&
        Objects.equals(this.v, postTransaction.v) &&
        Objects.equals(this.nonce, postTransaction.nonce) &&
        Objects.equals(this.chainId, postTransaction.chainId) &&
        Objects.equals(this.metadata, postTransaction.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hash, gasLimit, codeOrData, gasPrice, to, from, value, r, s, v, nonce, chainId, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostTransaction {\n");
    
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    gasLimit: ").append(toIndentedString(gasLimit)).append("\n");
    sb.append("    codeOrData: ").append(toIndentedString(codeOrData)).append("\n");
    sb.append("    gasPrice: ").append(toIndentedString(gasPrice)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    r: ").append(toIndentedString(r)).append("\n");
    sb.append("    s: ").append(toIndentedString(s)).append("\n");
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
