/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * PostCompileResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class PostCompileResponse {

  @JsonProperty("contractName")

  private String contractName = null;

  @JsonProperty("codeHash")

  private String codeHash = null;
  public PostCompileResponse contractName(String contractName) {
    this.contractName = contractName;
    return this;
  }

  

  /**
  * Get contractName
  * @return contractName
  **/
  @Schema(required = true, description = "")
  public String getContractName() {
    return contractName;
  }
  public void setContractName(String contractName) {
    this.contractName = contractName;
  }
  public PostCompileResponse codeHash(String codeHash) {
    this.codeHash = codeHash;
    return this;
  }

  

  /**
  * Get codeHash
  * @return codeHash
  **/
  @Schema(required = true, description = "")
  public String getCodeHash() {
    return codeHash;
  }
  public void setCodeHash(String codeHash) {
    this.codeHash = codeHash;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostCompileResponse postCompileResponse = (PostCompileResponse) o;
    return Objects.equals(this.contractName, postCompileResponse.contractName) &&
        Objects.equals(this.codeHash, postCompileResponse.codeHash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractName, codeHash);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostCompileResponse {\n");
    
    sb.append("    contractName: ").append(toIndentedString(contractName)).append("\n");
    sb.append("    codeHash: ").append(toIndentedString(codeHash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
