/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;

/**
 * Storage
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class Storage {

  @JsonProperty("storageAddress")

  private String storageAddress = null;

  @JsonProperty("storageKey")

  private File storageKey = null;

  @JsonProperty("storageValue")

  private File storageValue = null;

  @JsonProperty("storageChainId")

  private String storageChainId = null;
  public Storage storageAddress(String storageAddress) {
    this.storageAddress = storageAddress;
    return this;
  }

  

  /**
  * Get storageAddress
  * @return storageAddress
  **/
  @Schema(required = true, description = "")
  public String getStorageAddress() {
    return storageAddress;
  }
  public void setStorageAddress(String storageAddress) {
    this.storageAddress = storageAddress;
  }
  public Storage storageKey(File storageKey) {
    this.storageKey = storageKey;
    return this;
  }

  

  /**
  * Get storageKey
  * @return storageKey
  **/
  @Schema(required = true, description = "")
  public File getStorageKey() {
    return storageKey;
  }
  public void setStorageKey(File storageKey) {
    this.storageKey = storageKey;
  }
  public Storage storageValue(File storageValue) {
    this.storageValue = storageValue;
    return this;
  }

  

  /**
  * Get storageValue
  * @return storageValue
  **/
  @Schema(required = true, description = "")
  public File getStorageValue() {
    return storageValue;
  }
  public void setStorageValue(File storageValue) {
    this.storageValue = storageValue;
  }
  public Storage storageChainId(String storageChainId) {
    this.storageChainId = storageChainId;
    return this;
  }

  

  /**
  * Get storageChainId
  * @return storageChainId
  **/
  @Schema(description = "")
  public String getStorageChainId() {
    return storageChainId;
  }
  public void setStorageChainId(String storageChainId) {
    this.storageChainId = storageChainId;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Storage storage = (Storage) o;
    return Objects.equals(this.storageAddress, storage.storageAddress) &&
        Objects.equals(this.storageKey, storage.storageKey) &&
        Objects.equals(this.storageValue, storage.storageValue) &&
        Objects.equals(this.storageChainId, storage.storageChainId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storageAddress, storageKey, storageValue, storageChainId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Storage {\n");
    
    sb.append("    storageAddress: ").append(toIndentedString(storageAddress)).append("\n");
    sb.append("    storageKey: ").append(toIndentedString(storageKey)).append("\n");
    sb.append("    storageValue: ").append(toIndentedString(storageValue)).append("\n");
    sb.append("    storageChainId: ").append(toIndentedString(storageChainId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
