/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.TypeDefContract;
import com.blockchain.shipmentstrato.model.strato.TypeDefEnum;
import com.blockchain.shipmentstrato.model.strato.TypeDefStruct;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * User defined type (Struct or Enum)
 */
@Schema(description = "User defined type (Struct or Enum)")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class TypeDef {

  @JsonProperty("Enum")

  private TypeDefEnum _enum = null;

  @JsonProperty("Struct")

  private TypeDefStruct struct = null;

  @JsonProperty("Contract")

  private TypeDefContract contract = null;
  public TypeDef _enum(TypeDefEnum _enum) {
    this._enum = _enum;
    return this;
  }

  

  /**
  * Get _enum
  * @return _enum
  **/
  @Schema(description = "")
  public TypeDefEnum getEnum() {
    return _enum;
  }
  public void setEnum(TypeDefEnum _enum) {
    this._enum = _enum;
  }
  public TypeDef struct(TypeDefStruct struct) {
    this.struct = struct;
    return this;
  }

  

  /**
  * Get struct
  * @return struct
  **/
  @Schema(description = "")
  public TypeDefStruct getStruct() {
    return struct;
  }
  public void setStruct(TypeDefStruct struct) {
    this.struct = struct;
  }
  public TypeDef contract(TypeDefContract contract) {
    this.contract = contract;
    return this;
  }

  

  /**
  * Get contract
  * @return contract
  **/
  @Schema(description = "")
  public TypeDefContract getContract() {
    return contract;
  }
  public void setContract(TypeDefContract contract) {
    this.contract = contract;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypeDef typeDef = (TypeDef) o;
    return Objects.equals(this._enum, typeDef._enum) &&
        Objects.equals(this.struct, typeDef.struct) &&
        Objects.equals(this.contract, typeDef.contract);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_enum, struct, contract);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypeDef {\n");
    
    sb.append("    _enum: ").append(toIndentedString(_enum)).append("\n");
    sb.append("    struct: ").append(toIndentedString(struct)).append("\n");
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
