/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.blockchain.shipmentstrato.model.strato.FieldType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * TypeDefStruct
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class TypeDefStruct {

  @JsonProperty("bytes")

  private Integer bytes = null;

  @JsonProperty("fields")

  private List<List<FieldType>> fields = new ArrayList<>();
  public TypeDefStruct bytes(Integer bytes) {
    this.bytes = bytes;
    return this;
  }

  

  /**
  * Get bytes
  * minimum: 0
  * maximum: 384
  * @return bytes
  **/
  @Schema(required = true, description = "")
  public Integer getBytes() {
    return bytes;
  }
  public void setBytes(Integer bytes) {
    this.bytes = bytes;
  }
  public TypeDefStruct fields(List<List<FieldType>> fields) {
    this.fields = fields;
    return this;
  }

  public TypeDefStruct addFieldsItem(List<FieldType> fieldsItem) {
    this.fields.add(fieldsItem);
    return this;
  }

  /**
  * Get fields
  * @return fields
  **/
  @Schema(required = true, description = "")
  public List<List<FieldType>> getFields() {
    return fields;
  }
  public void setFields(List<List<FieldType>> fields) {
    this.fields = fields;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypeDefStruct typeDefStruct = (TypeDefStruct) o;
    return Objects.equals(this.bytes, typeDefStruct.bytes) &&
        Objects.equals(this.fields, typeDefStruct.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bytes, fields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypeDefStruct {\n");
    
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
