/*
 * STRATO API
 * This Swagger interactive documentation makes STRATO API calls to OAuth-protected STRATO demo node. Click 'Authorize' to sign-in with the test account.
 *
 * OpenAPI spec version: 4.5.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blockchain.shipmentstrato.model.strato;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Verify
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-07T11:36:15.752447+08:00[Asia/Shanghai]")public class Verify {

  @JsonProperty("uri")

  private String uri = null;

  @JsonProperty("timeStamp")

  private BigDecimal timeStamp = null;

  @JsonProperty("signers")

  private List<String> signers = null;
  public Verify uri(String uri) {
    this.uri = uri;
    return this;
  }

  

  /**
  * Get uri
  * @return uri
  **/
  @Schema(description = "")
  public String getUri() {
    return uri;
  }
  public void setUri(String uri) {
    this.uri = uri;
  }
  public Verify timeStamp(BigDecimal timeStamp) {
    this.timeStamp = timeStamp;
    return this;
  }

  

  /**
  * Get timeStamp
  * @return timeStamp
  **/
  @Schema(description = "")
  public BigDecimal getTimeStamp() {
    return timeStamp;
  }
  public void setTimeStamp(BigDecimal timeStamp) {
    this.timeStamp = timeStamp;
  }
  public Verify signers(List<String> signers) {
    this.signers = signers;
    return this;
  }

  public Verify addSignersItem(String signersItem) {
    if (this.signers == null) {
      this.signers = new ArrayList<>();
    }
    this.signers.add(signersItem);
    return this;
  }

  /**
  * Get signers
  * @return signers
  **/
  @Schema(description = "")
  public List<String> getSigners() {
    return signers;
  }
  public void setSigners(List<String> signers) {
    this.signers = signers;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Verify verify = (Verify) o;
    return Objects.equals(this.uri, verify.uri) &&
        Objects.equals(this.timeStamp, verify.timeStamp) &&
        Objects.equals(this.signers, verify.signers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uri, timeStamp, signers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Verify {\n");
    
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    timeStamp: ").append(toIndentedString(timeStamp)).append("\n");
    sb.append("    signers: ").append(toIndentedString(signers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
